set TECH_FILE    ${TECH_DIR}/smic18_6lm.tf
set GDS_MAP      ${TECH_DIR}/smic18_6lm.gds.map
set ANTENNA_RULE ""
set CALIBRE_RC   ""

set SITE_NAME       smic18site
set MIN_ROUTE_LAYER METAL1
set MAX_ROUTE_LAYER METAL6
set PIN_LAYERS      {METAL2 METAL3 METAL4 METAL5}

set REFERENCE_LIBS [list ${REF_DIR}/smic18_lib.ndm ${REF_DIR}/smic18_fill.ndm]
set STD_GDS        [list ${REF_DIR}/smic18.gds2]
set STD_CDL        ${REF_DIR}/smic18.cdl
set STD_VERILOG    ${REF_DIR}/smic18.v
set FORMALITY_DB_FILES [list ${REF_DIR}/slow.db]
set PDK_DFT_TARGET_DB $FORMALITY_DB_FILES
set PDK_ATPG_VERILOG  $STD_VERILOG
set PDK_DFT_SEARCH_PATH [list ${REF_DIR}]

set FILLER_CELLS  {*/FILL64 */FILL32 */FILL16 */FILL8 */FILL4 */FILL2 */FILL1}
set TIE_CELLS     {*/TIEHI */TIELO}
set ANTENNA_CELLS {}

set PG_POWER_NET  VDD
set PG_GROUND_NET VSS
set PG_RING_H_LAYER METAL5
set PG_RING_V_LAYER METAL6
set PG_RING_WIDTH 2.0
set PG_RING_SPACING 1.0
set PG_MESH_H_LAYER METAL5
set PG_MESH_V_LAYER METAL6
set PG_MESH_WIDTH 1.0
set PG_MESH_PITCH 30
set PG_MESH_OFFSET 5
set PG_BRIDGE_LAYER METAL4
set PG_BRIDGE_WIDTH 0.6
set PG_BRIDGE_PITCH 30
set PG_BRIDGE_OFFSET 5
set PG_RAIL_LAYER METAL1
set CTS_NDR_LAYERS {METAL3 METAL4 METAL5}
set CTS_NDR_WIDTH 0.56
set CTS_NDR_SPACING 0.56
set CTS_MIN_LAYER METAL3
set CTS_MAX_LAYER METAL5
set MAX_TRANSITION ""

set MCMM_MODE func
set SCEN_SETUP func_ss_1p62v_125c
set SCEN_HOLD  $SCEN_SETUP
set SCEN_TT    $SCEN_SETUP
set SCEN_LEAK  $SCEN_SETUP
set PNR_CORNERS [list \
    [list ss $SCEN_SETUP "" 1.62 125 typical true true true true]]

set PARASITIC_ENABLED 1
set TLU_MAP     ""
set TLU_TYPICAL ${TECH_DIR}/smic18_typical.tluplus
set TLU_CWORST  $TLU_TYPICAL
set TLU_CBEST   $TLU_TYPICAL
set STARRC_ITF_TYPICAL ${ROOT_PATH}/scripts/signoff/smic18_typical.itf
set STARRC_ITF_CWORST  $STARRC_ITF_TYPICAL
set STARRC_ITF_CBEST   $STARRC_ITF_TYPICAL
set STARRC_LEF_FILES [list ${TECH_DIR}/smic18_6lm.lef]
set CALIBRE_LVS_RC_DECK ""
set STARRC_MAP ${ROOT_PATH}/scripts/signoff/starrc.map
set TLU_SPECS [list [list typical $TLU_TYPICAL]]
